### ISSUE TITLE
The above error occurred in the <ThirdwebSDKProvider> component:

### ISSUE THREAD

**Issue by realsbd** [thirdweb-example/vite-javascript-starter#1]
I clone the repository and import all dependencies. I got this error message after running  `npm run dev`

> Uncaught ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
    at new ThirdwebSDK (sdk.ts:40:11)
    at Provider.tsx:355:18
    at mountMemo (react-dom.development.js:15846:19)
    at Object.useMemo (react-dom.development.js:16219:16)
    at useMemo (react.development.js:1532:21)
    at ThirdwebSDKProvider (Provider.tsx:351:15)
    at renderWithHooks (react-dom.development.js:14985:18)
    at mountIndeterminateComponent (react-dom.development.js:17811:13)
    at beginWork (react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
ThirdwebSDK @ sdk.ts:40
(anonymous) @ Provider.tsx:355
mountMemo @ react-dom.development.js:15846
useMemo @ react-dom.development.js:16219
useMemo @ react.development.js:1532
ThirdwebSDKProvider @ Provider.tsx:351
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback2 @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
(anonymous) @ main.jsx:9
react-dom.development.js:20085 The above error occurred in the <ThirdwebSDKProvider> component:

    at ThirdwebSDKProvider (http://localhost:3000/node_modules/.vite/@thirdweb-dev_react.js?v=1af5d61e:86541:29)
    at Provider2 (http://localhost:3000/node_modules/.vite/@thirdweb-dev_react.js?v=1af5d61e:75123:5)
    at ThirdwebProvider (http://localhost:3000/node_modules/.vite/@thirdweb-dev_react.js?v=1af5d61e:86519:28)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:20085
update.callback @ react-dom.development.js:20118
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20736
commitLayoutEffects @ react-dom.development.js:23426
callCallback2 @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
(anonymous) @ main.jsx:9
sdk.ts:40 Uncaught ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
    at new ThirdwebSDK (sdk.ts:40:11)
    at Provider.tsx:355:18
    at mountMemo (react-dom.development.js:15846:19)
    at Object.useMemo (react-dom.development.js:16219:16)
    at useMemo (react.development.js:1532:21)
    at ThirdwebSDKProvider (Provider.tsx:351:15)
    at renderWithHooks (react-dom.development.js:14985:18)
    at mountIndeterminateComponent (react-dom.development.js:17811:13)
    at beginWork (react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)

**Comment by jarrodwatts** [comment]
This example should be fixed with my latest commit!
