### ISSUE TITLE
Starter Template is broken 

### ISSUE THREAD

**Issue by SebasG22** [thirdweb-example/vite-javascript-starter#2]
The starter template is broken due to dependency fetch:
```bash
index.js:504 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at node_modules/nofilter/lib/index.js (index.js:504:11)
    at __require2 (chunk-FKZU6AN4.js?v=74759e5a:47:50)
    at node_modules/cbor/lib/utils.js (utils.js:4:18)
    at __require2 (chunk-FKZU6AN4.js?v=74759e5a:47:50)
    at node_modules/cbor/lib/commented.js (commented.js:4:15)
    at __require2 (chunk-FKZU6AN4.js?v=74759e5a:47:50)
    at node_modules/cbor/lib/cbor.js (cbor.js:3:21)
    at __require2 (chunk-FKZU6AN4.js?v=74759e5a:47:50)
    at esm_shims.js:2:32
```

This also broke the cloud version  https://vite-javascript-starter.thirdweb-example.com/

**Comment by SebasG22** [comment]
Related 
https://github.com/thirdweb-example/vite-typescript-starter/issues/1
https://github.com/thirdweb-dev/typescript-sdk/pull/459

**Comment by jarrodwatts** [comment]
Thanks for raising this @SebasG22 

We had some issues with the most recent versions of our SDK being compatible with Vite. For now, I've made this example use versions that are compatible to get rid of this error.

sorry for the delay in response. I am now watching this repo on GitHub so should get notifications in the future!
